### ISSUE TITLE
Project groups

### ISSUE THREAD

**Issue by skiadas** [skiadas/BattleFTP#1]
- You are expected to work in groups of two. 
- Each of you will need to create an account on GitHub if you do not have one already.
- Leave a comment in this thread with the link to your GitHub nickname and your partner's GitHub nickname, using the "at" sign (for instance my nickname is @skiadas).

| Team Name | Area of responsibility | Members |
|-------------|----------------------|----------|
BH & TW Inc. | [AI](https://github.com/skiadas/BattleFTP/issues/9) | @walkert20 (Tyler), @Hayesb20 (Brian) |
| Team Red Mambas | [Combat](https://github.com/skiadas/BattleFTP/issues/13)  | @millerlu19 (Lucas), @kenjarna (Kenny) |
| Team Seafoam | [Unit](https://github.com/skiadas/BattleFTP/issues/15) | @umphreyc19 (Colin),  @GrahamLW (Graham) |
| Team Chops| [Inventory](https://github.com/skiadas/BattleFTP/issues/11) | @hedrickj19 (Jacob), @roec20 (Chris) |
| Team Winners | [State](https://github.com/skiadas/BattleFTP/issues/10) | @helmersj20 (Jonathan), @mundth19 (Hannah) |
| Team Environment | [Environment](https://github.com/skiadas/BattleFTP/issues/12) | @veasy62 (Terryion), @haflg19 (Gage) |
| Team XOR | [UI](https://github.com/skiadas/BattleFTP/issues/8) | @PatrickConboy (Patrick), @amartens181 (Alex) |
| Team Hat Trick Swayze | [Game](https://github.com/skiadas/BattleFTP/issues/14) | @haques18 (Sakib), @Wilcolvan (Cole) |

**Comment by Hayesb20** [comment]
@ScarlitViper @walkert20

**Comment by walkert20** [comment]
@walkert20
@ScarlitViper

**Comment by kenjarna** [comment]
@millerlu19
@kenjarna

**Comment by GrahamLW** [comment]
@umphreyc19
@GrahamLW 

Team Seafoam

**Comment by AMartens181** [comment]
Who Wants To Partner?

**Comment by hedrickj19** [comment]
@hedrickj19
@roec20

**Comment by mundth19** [comment]
@helmersj20
@mundth19

Team Winners

**Comment by veasy62** [comment]
@veasy62
@haflg19

**Comment by Wilcolvan** [comment]
@haques18
@vanderpohlw19

Team Hat Trick Swayze

**Comment by amartens181** [comment]
@PatrickConboy
@amartens181
Team XOR

**Comment by walkert20** [comment]
got our groups.
