### ISSUE TITLE
State

### ISSUE THREAD

**Issue by mundth19** [skiadas/BattleFTP#10]
responsible for maintaining, storing, and retrieving the game state.
brainstorming ideas:

Groups to work with:
Inventory
Unit
Environment

**Comment by millerlu19** [comment]
you will also have to work with us at combat because when damage is being taken from a user, it will go to you, and you all will decide how much health the user has left or if they have no health at all.

**Comment by helmersj20** [comment]
That would be more for unit, as they keep track of health for the user, we're similar to a save file or save state

**Comment by skiadas** [comment]
Keep in mind that a unit's health during combat may be different than its health out of combat (max health?). Unit is managing the max health stat, but it might fall to Combat to maintain the state of a unit in combat, or in any case you need to sort it out.

Does a unit's health revert to full out of combat, or would that involve more complex actions (potions, eating, whatnot)?

**Comment by GrahamLW** [comment]
@skiadas I had assumed that there would be no full heals as soon as combat is done. How much health they have left allows us to make easier fights that don't kill right away, but do in aggregate. It adds depth with risk vs reward (should we go back and heal in safety or try to push our luck) without us having to code that much more.

**Comment by skiadas** [comment]
That's certainly a reasonable approach. In that case it makes sense for Unit to be the only one to maintain the unit's health. They will likely still have to maintain some sort of "max health" value around.

**Comment by amartens181** [comment]
Resistance: Fall of Man style
