### ISSUE TITLE
Environment Development

### ISSUE THREAD

**Issue by ghost** [skiadas/BattleFTP#12]
Groups to Work With:
* Game
* UI
* State

Information Needed:
* current stage/location
* starting location

Possible Ideas:
* environmental buffs
* random drops between rounds
* environmental "events"
    * walking into other students (fight? gifts?)
    * randomly finding items
    * finding bosses

**Comment by kenjarna** [comment]
If someone "falls off the map" we need to know so we can effectively "kill" the player. 100% damage. Done. Outta here.

**Comment by umphreyc19** [comment]
Are we going to have an actual currency in the game?

**Comment by ghost** [comment]
Feel like that would be up to Game, but we can add things for it if we have it. But I think that goes beyond the Environment

**Comment by ghost** [comment]
New Ideas:
* difficulty
    * as you get further from the start each 'block' or location on the map gets more difficult
    * need thoughts from Game/Combat/AI
* map
    * some sort of map function to display a map to the UI or for use in other ways
    * need thoughts from UI
* location
    * internally the game is viewed as a grid, where each 'block' has its own value to designate Outside, Inside, Out of Bounds, *etc...*
* obstacles
    * random things like rocks, trees, *etc...* throughout each location 'block' that the player may be able to interact with
    * need thoughts from Game/Unit
