### ISSUE TITLE
Define and Export your module's data types

### ISSUE THREAD

**Issue by skiadas** [skiadas/BattleFTP#18]
As a first step, we should define on each module what we consider to be the primary types that the module would need to use, and which of these types we must export. Each team must do the following:

- Create an issue for discussing the types in their module. Add a description of these types in the issue description. Make sure to note whether these types are:
    - **Internal types** for your module only, completely hidden from other modules.
    - **Opaque types** that other modules which import your module can see, and use in type signatures for example. But without direct access to the type variants. Other modules will not be able to do pattern-matching on the type variants, and they will rely on functions you provide to them in order to create values of this type and to work with these values.
    - **Transparent types**, that other modules which import your module can fully see, including the different type variants. Modules can then fully work with and create values of this type. But you must be careful when you modify such types, as other modules might be using their internals. In other words,  these types belong not just to your team but to all teams that use them.
- If your module uses other modules, then look at their type descriptions, and comment on their issues. Offer ideas, and discuss what you would need from those modules in order to do your work.

**Comment by walkert20** [comment]
Still exporting, but practically there.
