### ISSUE TITLE
Inventory Data Types

### ISSUE THREAD

**Issue by hedrickj19** [skiadas/BattleFTP#21]
Here is what I currently am thinking for the data types involving Inventory. I will probably add to these, but want to get my preliminary thoughts posted, so the rest of the class can give feedback.

- Storage/Inventory - what the user it currently carrying in his bag, this is will a be a list of type Item with a maximum length the simulate the size of the users bag, will be an opaque type to allow other modules to access and change a user's inventory through methods that Chris and I create

- ItemType -  describes the class of an item such as weapon, armor, shield, etc., this will be an internal type and only used by the Inventory group 
 data ItemType = weapon | shield | armor|.....

- Item - this is the type of an individual object such as a sword or shield, will be another opaque class with methods allowing other groups to use the objects of type Item, would be implemented as tuple such as (sword, weapon, 50, 0, -5) in the form (name, ItemType, Ints effecting individual attributes of a unit).

**Comment by skiadas** [comment]
Type and constructor/variant names must start with capital letters. So maybe `ItemType` rather than `iType`.

**Comment by walkert20** [comment]
Currently what we have for the AI data types:
     **type AI** - This will basically be of the same type as whatever the 'Unit' team decide their Units to be.  This may not be needed , however Unit's type will be what we accept in order to work.  It will be Opaque due to other functions needing to know what we accept.  
          **Ex**: type AI = Unit

     **type AI_action** - This will be the inner workings of the AI.  It will accept an AI/Unit and will return an appropriate action call based on conditions with "action" being whatever 'Combat' team has it to be.  Action will come from a list of possible moves the specific AI Unit can perform.  This will be Internal, meaning no touchy ("Hands off my madness!")
        **Ex**: type AI_action = AI/Unit -> (AI/Unit, action)  
**note**: It will not actually return a tuple.  This is just a place holding representation of what will happen, as to say we will accept a Unit and return the same Unit, but with a call to an action.

**Comment by PatrickConboy** [comment]
Seems like you covered most of your bases here. I personally can't think of anything else you'd need to add. Just gotta make sure you have all the methods for Storage implemented so other groups can change stuff properly. I don't think that'll be too hard, though.

**Comment by hedrickj19** [comment]
We were thinking that at least when we are getting started, items will  just affect a units attributes (such as attack, defense, speed, etc.) rather than having different actions for each weapon.

**Comment by Wilcolvan** [comment]
Sup Chops Hat Trick Swayze here we outlined an idea for the main game plotline in our issue. For that plotline we would need a number of "special" items including three pieces to the Sword of a Thousand Truths, the completed item of the Sword of a Thousand Truths, and keys.

**Comment by kenjarna** [comment]
For simplicity's sake, weapons/items should just affect the stats. So, the state team will have to keep track of current "state" of the characters, UI, etc. so that we can access the most recent information and do the appropriate actions. @mundth19

**Comment by mundth19** [comment]
we (state) are planning on keeping track of what inventory has/doesn't have in their inventory and updating it as necessary @kenjarna

**Comment by hedrickj19** [comment]
Sounds good.

**Comment by hedrickj19** [comment]
5b62a6b6b9c10393b9586391fc80a08a3abf829e
d1ef9a91e656a2d8a133f5cff2bdb28169b579b2
d1b7d9414d53e67997c983106f1ad7e33e7a1636
04a0decce89e85e96843c347170d8f926c248cf5

**Comment by hedrickj19** [comment]
696a9ac5e23dd24bcb2e69496c8a3c50164aa601
b594e2413e7c4c29bc8bb83d78ec92aecbd652ac
