### ISSUE TITLE
AI Data types

### ISSUE THREAD

**Issue by walkert20** [skiadas/BattleFTP#22]

**Comment by walkert20** [comment]
Currently what we have for the AI data types:
1. type AI - This will basically be of the same type as whatever the 'Unit' team decide their Units to be. This may not be needed , however Unit's type will be what we accept in order to work. It will be Opaque due to other functions needing to know what we accept.
Ex: type AI = Unit
2. type AI_action - This will be the inner workings of the AI. It will accept an AI/Unit and will return an appropriate action call based on conditions with "action" being whatever 'Combat' team has it to be. Action will come from a list of possible moves the specific AI Unit can perform. This will be Internal, meaning no touchy ("Hands off my madness!")
Ex: type AI_action = AI/Unit -> (AI/Unit, action)
note: It will not actually return a tuple. This is just a place holding representation of what will happen, as to say we will accept a Unit and return the same Unit, but with a call to an action.
@walkert20

**Comment by skiadas** [comment]
One thing to think about is what input the AI module would need to make a decision on what action to take. One of your main types should be discussing exactly this. Off the top of my head I imagine at minimum the current unit as well as the collection of allies and enemies of the unit. You should have the option to program your AI unit to for example attack the weakest enemy, or heal the most injured ally. So think of what data input you would need from Combat for that, even if you don't end up using it all now. It will *not* be easy to change that later.

**Comment by walkert20** [comment]
good.
