### ISSUE TITLE
Combat Types

### ISSUE THREAD

**Issue by kenjarna** [skiadas/BattleFTP#23]
As it currently stands, we have twotypes

1. Damage_Type...if we want to make users more susceptible to certain types of damage, then we will need a damage type. This is probably best used as an Opaque type
2. If we decide to do any sort of lasting effects, we will need to keep track of that somehow, so an effect type would be useful in that case, but it depends on what the unit/inventory/ai guys are thinking about

If there are other types anyone else thinks we should have, please let us know and we can discuss!

**Comment by skiadas** [comment]
I would focus on at most two damage types (physical vs mental perhaps?)

How are you managing the combat steps? I imagine you would need a data structure to maintain the state of combat as it evolves, things like all the involved units and their statuses, how you determine whose turn it is next etc.

What would the "output" of a combat be?

**Comment by hedrickj19** [comment]
We have ideas for items in this issue is you need to see what we are thinking. #21
