### ISSUE TITLE
Environment Types Ideas

### ISSUE THREAD

**Issue by ghost** [skiadas/BattleFTP#25]
## Internal Types (Environment Module Only)
* None?

## Opaque Types (Importers Limited Visibility)
* Location
    * Location type for designating things like being Outside, Inside, Out of Bounds, *etc...*
    * Something like this: `type Location = (Type, Diff)` where Type is Inside/Outside/*etc*
    * Possibly: `type Location = (Type, Diff, Up, Left, Down, Right)` to help UI when displaying
    * [x] State needs location for when saving the Game, as well as saving the Environment when entering a building (*ie* going inside while raining, then going outside, it should still be raining, probably)
    * [x] UI might need access if there is some sort of map functionality
    * [ ] Unit might need access if they can interact with the Environment (*ie* swim across river, climb tree, *etc...*)

## Transparent Types (Importers Full Visibility)
* Weather
    * Weather type for designating the games current weather (*ie* rain, wind, snow, *etc...*)
    * Something like this: `data Weather = Rain | Wind | Snow | Clear`
    * [x] Combat would need access to see what the weather is during battles
    * [x] UI would need access if they are going to draw what the weather is on screen
    * [x] State would need limited access
    * [ ] Unit may need some access if they can check weather to make certain decisions (*ie* armor that blocks wind debuffs, or something similar)?

**Comment by Wilcolvan** [comment]
Hello Team Environment! Team Hat Trick Swayze (Game Team) here. We outlined the basic game plot line in our issue, and if we are going to use it we will need "maps" or environments for the following areas: the Point, Parker Building, the CC, Science Hall, Science Center, the Library, Hendricks, CFA, and Scenic Drive

**Comment by Wilcolvan** [comment]
The absolutely essential environments are Scenic, the library (3 levels as big or as small as you want), the CC (the first level and basement level with bookstore included), Parker (2 levels), and the Point
