### ISSUE TITLE
State data types

### ISSUE THREAD

**Issue by helmersj20** [skiadas/BattleFTP#26]
Output_datatype: collects all data and returns it to game.

Organizational data types to maintain data from other groups.

Uses data types from environment, unit, and inventory.

Are there any other data types we need to store and return to game?

**Comment by kenjarna** [comment]
Are you keeping track of how weapons affect a character's stats? In other words, if the character equips a dagger, does combat need to apply the stats to the character to affect damage output, or are you just handing us the character with the dagger-influenced stats?
