### ISSUE TITLE
Game name and theme

### ISSUE THREAD

**Issue by skiadas** [skiadas/BattleFTP#3]
We need to come up with a good name for the game, or we'll be stuck with **HanoverRPG** forever. Each student should create an issue. In it you can do one of two things:

1. Suggest a name, and discuss some theme elements for the game. Put your name in bold by enclosing it in double-asterisks: `**HanoverRPG**`
2. Upvote a previous name, and expand on the elements suggested earlier for that name.

Suggested names so far:

- CSs bane
- BattleHanover
- Something like Canyon Defense and Motherload

Possible things to add:

- Food
- Locations/Areas
- Weapons

**Comment by Hayesb20** [comment]
**CSs bane**
Attack and defense types
Light
Dark
Fire
Water
Earth
Air

**Comment by Hayesb20** [comment]
oh and Ice

**Comment by walkert20** [comment]
**BattleHanover**
Theme elements:
1. Area in which battle(s) take place
2. Weapons if possible

**Comment by amartens181** [comment]
Canyon Defense and Motherload are the best games on miniclip
Something ***like*** one of those 🤔

**Comment by helmersj20** [comment]
@walkert20 We should add food

**Comment by mundth19** [comment]
@walkert20 I like that title but we I think we might need more elements -- not sure what though

**Comment by amartens181** [comment]
@helmersj20 We should add invincibility food

**Comment by kenjarna** [comment]
@walkert20 I like that name too. What if we did a version of Oregon Trail, but modify it to fit Hanover's campus. So we have food, energy, and random events that happen (parties, social events, greek life, school, class, etc). We essentially try to survive a semester.

**Comment by roec20** [comment]
I like the name. I think adding few equipment boosts and health and energy/mana points will add depth to the game. Whoever said battling the CS professors as bosses or what not I like that idea as well.

**Comment by hedrickj19** [comment]
I like the idea of making it Hanover themed. We can have the map locations named after buildings on campus. I also like the idea of adding different events such as parties, test, and sporting events. We could even think about making "bosses" named after facility members.

**Comment by PatrickConboy** [comment]
**Battle for the Point**
I'm thinking something like a very linear rpg would be the easiest to implement. Simply start out at point A, traverse through the linear set of events/battles, and have a final boss/fight/whatever to end the game. We could add checkpoints after each battle.

**Comment by GrahamLW** [comment]
The main gig should be fighting and exploration, all the design should focus on that. Events are cool, but how do they make the combat/dungeon exploration better or more interesting. Also, decisions that add depth for little complexity and less work on our end, should be heavily emphasized.

**Comment by veasy62** [comment]
**panthrpg**

If we go with locations based on campus locations like @hedrickj19 said, then we could have turn based boss fights with bosses named/designed after the CS professors.
- Team Enviroment

**Comment by haques18** [comment]
**HauntedHanover**

Hanover College has fallen victim of a zombie attack. The President, Lake Lambert, has hidden the cure to the zombie epidemic somewhere on campus before he turned into a zombie himself. You are one of the last human survivors. Your mission, should you choose to accept is to find the cure and save the campus before getting caught and killed by the zombies. You don't know what the cure looks like, or where it is hidden, but you do remember talking to Dr. Lambert about how he has hidden the map that leads to the cure behind the Declaration of Independence show cased in front of the CFA.

Game Goals:
1. Extract the Declaration of Independence
2. Run to the Chemistry Lab and use chemicals to make the map visible.
3. Decipher the map to find where the cure is hidden.
4. Extract the cure.

Now that you have the cure, the next step is to find patient Zero of the epidemic and applying the cure to him/her. If you apply the cure to the wrong person (some other human turned zombie that is not patient Zero), you will die, thus resulting in termination of the game. The information about Patient Zero is hidden in the confidential documents in the health services office.

Part 2 goals:
1. Find the documents that have the information about Patient Zero. But of course there were 4 people who were diagnosed with the zombie symptoms on day 1.
2. Now that you have narrowed down the suspects to 4 people, and that you have read up on how the zombie virus works, apply your knowledge on the 4 patients' history that you read from their medical history files and the information about the virus to deduct who is patient Zero. Remember, if you apply the cure to the wrong patient, you WILL die. But if you successfully apply the cure without getting killed by zombie's in the middle of each of your missions, you win and save Hanover College and the Hanover CS department will change its name to commemorate your contribution to the campus community.

**Comment by Wilcolvan** [comment]
I like Sakib's idea, but I would add on that the head of every Department is a boss in the game, with abilities that suit their area of expertise. In the story, the head of each department collaborated with the president to hide the cure.

**Comment by umphreyc19** [comment]
I like the idea of just doing something fantasy based. It keeps the project simple and since it would be fantasy, we could have a much wider range of ideas to collaborate on.

**Comment by umphreyc19** [comment]
I like the idea of just doing something fantasy based. It keeps the project simple and since it would be fantasy, we could have a much wider range of ideas to collaborate on.

**Comment by skiadas** [comment]
Closing this as we have settled on a name.
