### ISSUE TITLE
UI Discussion

### ISSUE THREAD

**Issue by PatrickConboy** [skiadas/BattleFTP#38]
Okay, I'm trying to better visualize what UI is necessarily doing. In my eyes, UI will take in information from other modules and display that information to the user. We will then take an input(s) from the user and pass the input on to other modules to use. From our discussions in class it sounded like UI was going to be expected to call on other modules to actually do combat, events, etc. in our module. This doesn't match up with what I was imagining. It almost sounds like we are combining the main "game" executable and UI into one module. Do we have a main executable outside of UI? 

These are just my collection of thoughts on UI. I need to get a better understanding of what exactly UI needs to accomplish. Please leave your thoughts!

**Comment by amartens181** [comment]
@PatrickConboy We're not going to call all functions. But we are going to call functions that will call the other functions and give us the results through the chain. 
Game is in charge of making the _final_ exe but I think their job is more of just plugging the deps and making sure everything runs. **UI** will be **most** _important_ in the final exe but we're _not exactly_ in charge of that. Maybe we can get game to create the interaction logic module that will put everything together but I'm not sure. Everything kind of depends on how complex it is going to be. _probably not **very**_
