### ISSUE TITLE
Name suggestion: BattleHanover

### ISSUE THREAD

**Issue by skiadas** [skiadas/BattleFTP#4]
One of the suggested names that gained some traction was BattleHanover. Use this issue to expand on the idea more.

**Comment by walkert20** [comment]
This may be favoritism, but it just has a certain ring to it is all.  CSbane isn't all that bad either.  I just find BattleHanover somewhat more appealing.

**Comment by skiadas** [comment]
@walkert20 It also suggests a different theme though. BattleHanover makes me think of something that takes place at Hanover, maybe as @kenjarna suggested something related to the students' struggles towards graduation, or something of that sort? Is that the direction you had in mind, or something else?

**Comment by GrahamLW** [comment]
I like the idea of it taking place on Hanover. Something like a dungeon is discovered in an academic building, and a club is started, the Hanover Exploration Club. Would give us a grounded idea for any game world we might want. Could make classes based on Majors. Best of all, it's straightforward. Just make some stores of an overworld and a deep dungeon.

**Comment by amartens181** [comment]
@GrahamLW Are you suggesting a copy of Sword Art?

**Comment by walkert20** [comment]
I just thought that it would be easier if it took place at Hanover due to source material and simplicity.  The areas can be simply the quad, the WAC, and a party for areas of combat, and the UG, CC, and Bookstore could be places to buy items and food.

**Comment by hedrickj19** [comment]
I like the idea of making it based on Hanover's campus.

**Comment by helmersj20** [comment]
I think keeping it central to Hanover and students here would make the game easier to create. We wouldn't have to create too much original content as the school in a sense provides content for us.

**Comment by mundth19** [comment]
I like the simplicity of the name and think it's pretty self explanatory. Battle at the Point is pretty creative too; I definitely we should keep it related to Hanover so that it's a relevant project.

**Comment by millerlu19** [comment]
I agree with the idea that it can be held on Hanover's campus, whether its the entire campus or in our specific classroom with my idea on the README issue.  If we decide to use the whole campus, I like the idea of different levels being on different parts of campus.

**Comment by amartens181** [comment]
It definitely needs to be the whole campus. Outside environments are easier to create, anyway.

**Comment by Wilcolvan** [comment]
I really like Sakib's idea as far as game conceptualization, and if I had to name it, it would probably be "The Undead of Hanover" as a reference to "The Beauty of Hanover" in the saying "That's the beauty of Hanover."

**Comment by amartens181** [comment]
The name BattleFTP might get us some github traffic 😂

**Comment by skiadas** [comment]
Closing this as we have selected a name.
