### ISSUE TITLE
Track Visited Locations

### ISSUE THREAD

**Issue by ghost** [skiadas/BattleFTP#44]
We need a way to track places that the Player has visited in the game before, so they are not able to get Quest Items or other things by just revisiting that location on the Map.

Should we track this or should State track this? We thought of these ways to track it, not sure which is best?
* Within the map, mark a Block as visited when the player first enters that Block (ie. each Block has a `visited` attribute)
* Same as the first option except have the State object tracking it
* State object maintain a separate array of visited locations
* State/Game/someone else add a trait to the Quest Items on whether they have been taken by the Character previously, if True (or some other value) then they would not reappear when the player returns to that Location

**Comment by Wilcolvan** [comment]
Currently I don't think we want the player to revisit locations. It's certainly something that we can think about if we have time, but right now I think we should focus on getting the Hero to a location at least once. Our official input is that Environment should provide the list of locations but State should track which location the Player is at, but at the end of the day whether Player location is tracked by State or Environment is between Team Environment and Team Winners. When you guys figure it out Game will need to know.

**Comment by amartens181** [comment]
Whoever keeps track of movement can just prevent going back

**Comment by ghost** [comment]
First, see #59 to understand how we are currently planning on implementing the Environment module's types. We also need your input on a question there.

But as for this issue, we are going to have the `Env` type which contains the `Map` array and the player's `Location`, so it wouldn't be much of a stretch to have something like another Array at the end of this tuple that tracks all of the players movements to do something like what Alex suggested. But, I think this could cause other problems, like if the player loses a fight and gets set back, or if the player forgets to pick up an item in a `Block` and needs to return (unless we are just giving players the items, without them needing to do anything). But my main issue with something like this is that it would just mean storing a bunch of data that will likely never be used. However if my idea below isn't possible or wanted, then we can do it this way.

The way I think we should do this would basically be the fourth option in this original issue. I feel like this could be a much cleaner and more efficient solution. But basically, anything that should only be encountered once, can just add on another Boolean value which defaults to False. The value would then be flipped once the player takes the Item or defeats the Boss. When the player approaches the Item/Boss, the game would just check whether the value is True or False, and not display the Item/Boss if the value is True (*ie.* visited). I just think this way will be more immersive, efficient (vs storing an entire extra array for every `Block` on the `Map`), and allow more freedom than just preventing players from returning to places. This would also remove the doubt about whether the player was previously in a `Block` and forgot to grab an Item, or originally lost to a Boss (if we have something like checkpoints). Just another thing I thought of while writing this that is semi-related, is that whenever the player does go back to the location of the item/boss that they already took/beat the console message area could display something like "This is where I found the ...." or "This is where I defeated Professor ....".

I don't know how Inventory is currently setting up their types and functions so, obviously, if we are going to do something like what I just said, then we would need input from the Inventory and Unit/AI (whoever is making bosses) teams to make sure something like that would be possible with how they are doing items/bosses.

Just a couple things I had in mind. I don't mind doing it either way, just thought I'd flesh out that idea more since I personally feel like its the overall best solution, but it could be more work for other groups than I am thinking of right now. So if it is we can just do it the first way, where we store the Array of Locations that the player has visited and track it that way.

**Comment by Wilcolvan** [comment]
I know that in the Game Design Idea we stated that the Hero would need to escape from the campus after they rescued President Lambert from the Point, but we wanted to hold off on that idea until we actually get a game that gets us to the Point. In that sense, we don't really see anything to gain from allowing the Hero to revisit locations: the steps within the questline will be the Hero's only option in moving forward within the game, and quest items will be given to them. In that implementation we don't really see a need for a Boolean value to track whether or not an item/location has been accessed - unless it helps you guys code in which case go for it.

**Comment by Wilcolvan** [comment]
List of Locations (in order):
Scenic Drive
Library
CC
Parker
The Point
