### ISSUE TITLE
Detailed Environment Types and Functions

### ISSUE THREAD

**Issue by ghost** [skiadas/BattleFTP#59]
**Incomplete, just the main types and information right now, types may change slightly.**

Main types in the Environment Module:
```haskell
-- Types of Blocks in the Map
--     X = Out of Bounds | O = Outside | I = Inside
data Type = X | O | I
-- Possible Weather in game, used by Combat to effect battles
--     UI can use to display Weather to user
data Weather = Rain | Wind | Snow | Clear
-- Just used for semantics; used to get the floor of players current building
--     Will always be 1 when outside, unless a reason arises to add 0 value for outside
data Floor = 1 | 2 | 3

-- Main type from Environment Module
--     Tracks current world map, player location, and weather
type Env = (Map, Location, Weather)
-- 2D Array of Block types which represents the actual Map itself
type Map = [[Block]]
-- (Current Block, Block Above, Block to Right, Block Below, Block to Left)
--     If UI does not need the surrounding 4 Block's information, this will be removed
type Block = (Type, Type, Type, Type, Type)
-- X and Y coordinate of the player, wrapped in tuple
type Location = (Num, Num)
```

Main functions in the Environment Module:
```haskell
-- Creates initial Environment tuple, intented to be called only when starting a game
initEnv :: Env

-- Simple getter functions to get the environment's current information
--     getLocation returns current Block, while getXY returns current (X, Y) position
getMap :: Env -> Map
getLocation :: Env -> Block
getXY :: Env -> Location
getWeather :: Env -> Weather

-- Updates the Location in an Env tuple when the player moves
--     Will likely change function to take String or something representing "Up", "Down"
--     Currently the function would take in the new Location, so something like (3, 5)
updateMap :: Env -> Location -> Env
```

**Comment by ghost** [comment]
@amartens181 @PatrickConboy 

Do you guys know what you are going to be doing about displaying the area around the character in game? Will you be displaying the `Block`s surrounding the players current location? If you guys are not then we will most likely remove the extra information from the `Block` type, which is explained in the comment above the type.

**Comment by Wilcolvan** [comment]
Here's what Game was thinking: we weren't really planning on having weather, as only 2 out of the 5 locations that we were thinking were outside, and we didn't really want weather to change because we think that the play through should be consistent. So I don't think we need Type or Weather.
As for player location, we didn't think there would be a block system. We had envisioned multiple floors, but once a player was on a specific floor in a specific building they wouldn't have to move. Any "movement" in the floor would be implied or written out.
