### ISSUE TITLE
Name Suggestion: Battle at the Point or Battle for the Point

### ISSUE THREAD

**Issue by PatrickConboy** [skiadas/BattleFTP#6]
Not sure what to comment here. Title self explanatory? Let's go with that.

**Comment by hedrickj19** [comment]
I like the name Battle for the Point.

**Comment by millerlu19** [comment]
I like Battle for the Pointe as well.  I vote either this title or BattleHanover

**Comment by roec20** [comment]
I like Battle for the Point

**Comment by mundth19** [comment]
I like this name or Battle Hanover

**Comment by kenjarna** [comment]
I say we go with this name. I think we're supposed to decide for tomorrow, so I vote for this one.

**Comment by PatrickConboy** [comment]
Battle for the Point works for me :)

**Comment by Wilcolvan** [comment]
This game type isn't necessarily my first choice, but since everyone likes it I wouldn't mind going with it

**Comment by skiadas** [comment]
Closing this as we have settled on this name.
