### ISSUE TITLE
UI Development

### ISSUE THREAD

**Issue by amartens181** [skiadas/BattleFTP#8]
This is about what I envision our UI to be:
![image](https://user-images.githubusercontent.com/16763643/32583963-11d82510-c4c4-11e7-9b97-4f5ae2595e29.png)

<details> 
  <summary>I would like to find a way to use CEF</summary>
(I dare you to tell me a better design than what web technologies has to offer. CSS/HTML/JS are simply the best way to make scalable, cross platform applications.)
</details> 
I've found [this](https://github.com/haskell-ui/cef3-raw)

**Comment by umphreyc19** [comment]
What kind of options are we going to have outside of battle and inside of battle?

**Comment by amartens181** [comment]
@umphreyc19 Probably just copy Pokemon or Arena

**Comment by skiadas** [comment]
You can do some fancy text-based stuff with this module:

https://hackage.haskell.org/package/ansi-terminal-0.7.1.1/docs/System-Console-ANSI.html

**Comment by haques18** [comment]
Hey, Do you guys have any function that prompts the user to enter their name and return that string? Because game needs that to create character. Please and Thank you.
