### ISSUE TITLE
AI Brainstorming

### ISSUE THREAD

**Issue by walkert20** [skiadas/BattleFTP#9]
@walkert20
@Hayesb20

**Comment by haques18** [comment]
Hey AI, question. Are you at all determining what enemy hit chance and enemy damage rate is going to be? Or do you want us (game) to take care of that when we are creating characters?

**Comment by walkert20** [comment]
I don't think hit chance is being implemented at all.  I think combat is doing damage rate.  You might want to talk to them about it.
